name: eval and publish notebooks

on:
  schedule:
    - cron: "*/6 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  plot_vessel_and_buoy_pos:
    runs-on: ubuntu-22.04
    container:
      image: docker://pangeo/pangeo-notebook:2023.04.15
      options: --user 1001  # https://github.community/t/how-to-run-action-as-a-non-root-user/17572/2
    steps:
      - uses: actions/checkout@v1
      - name: Initialize conda
        run: bash -c "conda init bash"
      # - name: Restore cached buoy positions
      #   id: cache-buoy-positions-restore
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: |
      #       data/buoys
      #     key: buoy-positions
      - name: Run all notebooks with papermill
        run: |
          export TAO_FTP_USER=${{ secrets.TAO_FTP_USER }} 
          export TAO_FTP_PASS=${{ secrets.TAO_FTP_PASS }} 
          bash -c ". /srv/conda/etc/profile.d/conda.sh && conda activate notebook && python -m pip install papermill && .ci/run_all_notebooks.py --dir . --out ci_out/"
      # - name: Save buoy positions
      #   id: cache-buoy-positions-save
      #   uses: actions/cache/save@v3
      #   with:
      #     path: |
      #       data/buoys
      #     key: buoy-positions
      - name: Complete listing of data dirs
        if: ${{ always() }}
        run: |
          du -sh *
      - name: Convert to HTML
        if: ${{ always() }}
        run: |
          bash -c ". /srv/conda/etc/profile.d/conda.sh && conda activate notebook && cd ci_out/ && jupyter nbconvert --to HTML \*.ipynb"
      # - name: Upload notebook
      #   uses: actions/upload-artifact@v1
      #   if: ${{ always() }}
      #   with:
      #     name: ci_out
      #     path: ci_out/
      - name: Prepare pages
        run: |
          mkdir -p ./public
          cp ci_out/*.html ./public/.
          echo '<meta HTTP-EQUIV="REFRESH" content="0; url=020_plot_positions.html">' > ./public/index.html
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
